### ISSUE TITLE
Application crashes after user tries to return from app store

### ISSUE THREAD

**Issue by s-flores** [humboldt-cs/cs480-queue-rhythm#10]
When a user that does not have Spotify installed on their device tries to use QRhythm, they are automatically taken to the Play Store to download Spotify, but program stops working when trying to go back.

**Comment by amandarose42** [comment]
Pretty sure this is fixed. Ran two different tests:
1.) downloading spotify & logging in then returning to QR app, worked fine. 
2.) downloading spotify, returning to QR, being asked to log in, worked fine. 
               minor bug here: 
Have to click to queue page to handle auth currently(but that will change when mainactivity has spotify api use.)
