### ISSUE TITLE
Parsing results returns "No User" for user information and blank for recently played tracks

### ISSUE THREAD

**Issue by s-flores** [humboldt-cs/cs480-queue-rhythm#11]
I attempted to parse the data using Volley, but I'm not getting the right results.  My guess is that it might be related to the REDIRECT_URI I'm not sure if I am assigning the correct value to this which has to be "white listed" in our project at the Spotify dashboard. Other option would be to use the Android RestClientTemplate provided by CodePath.

**Comment by amandarose42** [comment]
There should be a REDIRECT URI in the main project

    private static final String REDIRECT_URI = "http://qr.example.com";
