### ISSUE TITLE
We have both a QR and  QRhythm directories in our repo

### ISSUE THREAD

**Issue by s-flores** [humboldt-cs/cs480-queue-rhythm#9]
After the merging the branches we ended up with two different project folders and we only need the QR. If we try to remove QRythm folder the program stops working.

**Comment by amandarose42** [comment]
Removed QRhythym App. QR can still run.

**Comment by s-flores** [comment]
I tried to merge your branch into the master and it still did not work. I downloaded your branch and added the QRhythm package back in but still merge conflicts related to .
DS_Store
QRhythm/app/src/main/java/com/example/queuerhythm/MainActivity.java
QRhythm/build.gradle

**Comment by s-flores** [comment]
I was able to resolve the merge conflicts. Our latest work is now in up on the master branch
